#!/usr/bin/env python
import pygtk
pygtk.require('2.0')
import gtk
import gtk.gdk
import gobject
import gtk.glade
import gnome
import gnome.ui
from environment import env

from kofoto.imagecache import *
from kofoto.sets import *

from albums import *
from images import *
from mainwindow import *
from tableview import *
from thumbnailview import *
from singleimageview import *
from categories import *


######################################################################
### Classes

class WidgetsWrapper:
    def __init__(self):
        gnome.init("GKofoto", "0.0001")
        self.widgets = gtk.glade.XML(env.gladeFile, "mainWindow")
    def __getitem__(self, key):
        return self.widgets.get_widget(key)
    def signal_autoconnect(self, dic):
        self.widgets.signal_autoconnect(dic)

class Controller:
    loadedImages = None
    _loadedImagesTitel = ""
    _wantedThumbnailSize = None
    _tableView = None
    _thumbnailView = None
    _singleImageView = None
    _categories = None
    selection = Set()
    _currentImageView = None
    _hiddenImageViews = []
    _clipboard = None

    def __init__(self):
        self._wantedThumbnailSize = 100 # TODO: Calculate from dropdown menu in the GUI
        
    def start(self):
        albums = Albums()
        self._categories = Categories()
        self._thumbnailView = ThumbnailView()
        self._tableView = TableView()
        self._singleImageView = SingleImageView()
        self.newDataModel()
        self.showThumbnailView()
        MainWindow()
        env.widgets["mainWindow"].connect('destroy', self.quit, gtk.FALSE)
        env.widgets["mainWindow"].show()
        env.shelf.begin()
        gtk.main()

    def quit(self, gnomeApp, cancelButton=gtk.TRUE):
        if env.shelf.isModified():
            widgets = gtk.glade.XML(env.gladeFile, "quitDialog")
            quitDialog = widgets.get_widget("quitDialog")
            if not cancelButton:
                widgets.get_widget("cancel").set_sensitive(gtk.FALSE)
            result = quitDialog.run()
            if result == 0:
                print "commit"
                env.shelf.commit()
                gtk.main_quit()
            elif result == 1:
                print "rollback"
                env.shelf.rollback()
                gtk.main_quit()
            else:
                quitDialog.destroy()
                return
        else:
            print "rollback"
            env.shelf.rollback()
            gtk.main_quit()

    def save(self, gnomeApp):
        env.shelf.commit()
        print "commit"
        env.shelf.begin()
        
    def newDataModel(self):
        self.loadedImages = Images()
        self._tableView.setModel(self.loadedImages.sortedModel)
        self._tableView.setAttributes(self.loadedImages.attributeNamesMap)
        self._thumbnailView.setModel(self.loadedImages.sortedModel)
        self._singleImageView.setModel(self.loadedImages.sortedModel)
        
    def loadImages(self, imageList, source):
        env.widgets["sourceEntry"].set_text(source)
        self.selection.clear()
        self._currentView.freeze()
        self.loadedImages.loadImageList(imageList)
        self.loadedImages.loadThumbnails(self._wantedThumbnailSize)
        self._currentView.thaw()
        self._currentView.loadNewSelection()
        
    def selectionUpdated(self):
        self._currentView.loadNewSelection()
        self._categories.updateView()

    def _viewChanged(self):
        self._currentView.loadNewSelection()
        self._currentView.show()
        for hiddenView in self._hiddenViews:
            hiddenView.hide()
        
    def showTableView(self):
        self._currentView = self._tableView
        self._hiddenViews = [self._thumbnailView, self._singleImageView]
        self._viewChanged()
        
    def showThumbnailView(self):
        self._currentView = self._thumbnailView
        self._hiddenViews = [self._tableView, self._singleImageView]
        self._viewChanged()

    def showSingleImageView(self):
        self._currentView = self._singleImageView
        self._hiddenViews = [self._tableView, self._thumbnailView]
        self._viewChanged()
        
    def clipboardSet(self, object):
        self._clipboard = object
        self._categories.updateContextMenu()

    def clipboardClear(self):
        self._clipboard = None
        self._categories.updateContextMenu()

    def clipboardPop(self):
        popedItem = self._clipboard
        self._clipboard = None
        self._categories.updateContextMenu()
        return popedItem
        
    def clipboardHasCategory(self):
        if isinstance(self._clipboard, ClipboardCategories):
            return gtk.TRUE
        else:
            return gtk.FALSE
        
######################################################################
### Start

env.widgets = WidgetsWrapper()
env.controller = Controller()
env.controller.start()

        


