#! /bin/sh

if [ -L "$0" ]; then
    testdir=$(dirname $(readlink -f "$0"))
else
    testdir=$(dirname $0)
fi
$testdir/../cmdline/kofoto \
    --configfile=$testdir/test.conf \
    --shelf=$testdir/test.shelf \
    "$@"
