.TH KOFOTO 1
.SH NAME
kofoto \- a tool for organizing digital images

.SH SYNOPSIS
\fBkofoto\fP \fI[flags] <command> [parameters]\fP

.SH DESCRIPTION
\fIkofoto\fP is the command-line interface to Kofoto.

Kofoto is a tool for organizing and viewing digital images, typically
photographs from a digital camera. Images can be organized in an album
hierarchy and associated with categories organized in a powerful
category tree with no limits on depth or size. Images can be found by
searching for any combination of categories and image attributes. Web
photo albums of an album hierarchy can also be generated. Both
command-line and graphical, GTK+-based interfaces are available.

See \fIhttp://kofoto.rosdahl.net\fP for more information.

.SH OPTIONS
Run \fBkofoto --help\fP for usage information.

.SH "SEE ALSO"
\fBgkofoto\fP(1)

.SH BUGS
See \fIhttp://kofoto.rosdahl.net/trac/report\fP.

.SH AUTHORS
Written by Joel Rosdahl <joel@rosdahl.net> and Ulrik Svensson
<ulrik@kristnet.org>.
