#!/usr/bin/env python

import sys
import os

if sys.platform.startswith("win"):
    import _winreg
    import msvcrt
    try:
        k = _winreg.OpenKey(_winreg.HKEY_LOCAL_MACHINE, "Software\\GTK\\2.0")
    except EnvironmentError:
        print "You must install the Gtk+ 2.2 Runtime Environment to run this program"
        while not msvcrt.kbhit():
            pass
        sys.exit(1)
    else:
        gtkdir = _winreg.QueryValueEx(k, "Path")
        import os
        os.environ["PATH"] += ";%s/lib;%s/bin" % (gtkdir[0], gtkdir[0])

# Find libraries if installed in ../lib (like in the source tree).
if os.path.islink(sys.argv[0]):
    link = os.readlink(sys.argv[0])
    absloc = os.path.normpath(
        os.path.join(os.path.dirname(sys.argv[0]), link))
    bindir = os.path.dirname(absloc)
else:
    bindir = os.path.dirname(sys.argv[0])
sys.path.insert(0, os.path.join(bindir, "..", "lib"))
sys.path.insert(0, os.path.join(bindir, ".."))

from gkofoto.main import main
main(bindir, sys.argv)
