#! /usr/bin/env python

import EXIF
import os
import sys
import time

def getExifTimestamp(filename):
    tags = EXIF.process_file(file(filename, "rb"))
    for tag in ["Image DateTime", "EXIF DateTimeOriginal",
                "EXIF DateTimeDigitized"]:
        value = tags.get(tag)
        if value:
            return str(value).replace(":", "").replace(" ", "")
    return None

def getFileModificationTimestamp(filename):
    t = os.path.getmtime(filename)
    return time.strftime("%Y%m%d%H%M%S", time.localtime(t))

if len(sys.argv) < 2:
    print "Usage: renameimage file [file ...]"
    sys.exit(1)

for filename in sys.argv[1:]:
    if not os.path.isfile(filename):
        sys.stderr.write("Error: No file named %s; skipping.\n" % filename)
        continue
    timestamp = getExifTimestamp(filename)
    if not timestamp:
        sys.stderr.write("Warning: Found no EXIF timestamp in %s; using file modification timestamp.\n" % filename)
        timestamp = getFileModificationTimestamp(filename)
    os.rename(filename, "%s-%s" % (timestamp, filename))
